routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\IndexController;
use App\Http\Controllers\SiswaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

/**
 * Index page nya coba di seederhanakan dengan Index Controller
 */
Route::get('/', [IndexController::class, 'index'])->name('index');

/**
 * Dibuatkan grouping agar
 */
Route::group(['prefix' => 'siswa', 'as' => 'siswa.'], function(){
    /** Route mendapatkan list data */
    Route::get('', [SiswaController::class, 'index'])->name('index');
    /** Route memunculkan form saat create */
    Route::get('/create', [SiswaController::class, 'create'])->name('create');
    /** Route unutk mengeksekusi perintah menyimpan data yang telah diinputkan */
    Route::post('store', [SiswaController::class, 'store'])->name('store');
    /** Route untuk mendapatkan detail dari sebuha data */
    Route::get('{id}', [SiswaController::class, 'show'])->name('show');
    /** Route untuk melakukan proses pengeditan (memunculkan form edit) */
    Route::get('/{id}/edit', [SiswaController::class, 'edit'])->name('edit');
    /** Route update untuk melakukan eksekusi perintah update */
    Route::put('/{id}/update', [SiswaController::class, 'update'])->name('update');
    /** Route untuk melakukan eksekusi delete */
    Route::delete('{id}', [SiswaController::class, 'destroy'])->name('destroy');

    /**
     * NOTE :
     * semua penulisan di atas, dapat diganti dengan
     * Route::resource('', [SiswaController]);
     * 
     * Akan tetapi, kembali ke preferensi masing-masing.
     * Saya pribadi lebih suka mendefinisikan nya secara jelas
     */
});

app/Models/Prodi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Prodi extends Model
{
    use HasFactory;

    /**
     * Artinya, kolom id di proteksi, sehingga tidak bisa di nasukkan secara masal
     */
    protected $guarded = ['id'];

    /** Mendefinisikan kolom yang boleh di isi, ini untuk keperluan keamanan data */
    protected $fillable = ['nama'];
}

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;

    /**
     * Relasi ke table prodi
     */
    public function prodi()
    {
        return $this->belongsTo(Prodi::class, 'prodi_id', 'id');
    }
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class IndexController extends Controller
{
    public function index()
    {
        // return view('welcome');
        return view ('app.index');
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Repositories\SiswaRepository;
use App\Repositories\ProdiRepository;

use App\Http\Requests\SiswaCreateRequest;
use App\Http\Requests\SiswaEditRequest;
use App\Http\Requests\SiswaUpdateRequest;
use App\Http\Requests\SiswaDeleteRequest;

class SiswaController extends Controller
{
    /**
     * Pendefinisiaan class repository yang akan digunakan
     * @var SiswaRepository
     */
    private SiswaRepository $repo;

    /**
     * Pendifinisian class repository yang akan digunakan
     */
    private ProdiRepository $prodiRepo;

    /**
     * Melakukan init saat memanggil class siwa controller
     * @void
     */
    public function __construct()
    {
        $this->repo = app(SiswaRepository::class);
        $this->prodiRepo = app(ProdiRepository::class);
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $datas  = $this->repo->get();

        return view('app.siswa.index', [
            'datas' => $datas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $prodis = $this->prodiRepo->get();

        return view('app.siswa.create', [
            'prodis' => $prodis
        ]);
    }

    /**
     * Store a newly created resource in storage.
     * 
     * @param SiswaCreateRequest $request
     * 
     */
    public function store(SiswaCreateRequest $request)
    {
        /** Ambil inputan dari form */
        $input = $request->all();
        /** Lakukan action pembuatan data lewat class repository */
        $data = $this->repo->create($input);

        /** Redirect success ke store */
        return redirect()->route('siswa.index')->with('status', "Berhasil menambahkan data");

    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     * 
     * @param SiswaEditRequest $request
     * @param int $id
     */
    public function edit(SiswaEditRequest $request, int $id)
    {
        $data = $this->repo->findOne($id);
        $prodis = $this->prodiRepo->get();

        return view('app.siswa.edit', [
            'data' => $data,
            'prodis' => $prodis
        ]);
    }

    /**
     * Update the specified resource in storage.
     * @param SiswaUpdateRequest $request
     * @param int $id
     */
    public function update(SiswaUpdateRequest $request, int $id)
    {
        /** Ambil inputan dari form */
        $input = $request->all();
        /** Lakukan action update data */
        $data = $this->repo->update($id, $input);

        /** Redirect success ke update */
        return redirect()->route('siswa.index')->with('status', "Berhasil mengupdate data");
    }

    /**
     * Remove the specified resource from storage.
     * 
     * @param SiswaDeleteRequest $request
     * @param int $id
     * 
     */
    public function destroy(SiswaDeleteRequest $request, int $id)
    {
        $this->repo->destroy($id);
        return redirect()->route('siswa.index')->with('status', "Berhasil menghapus data");
    }
}

resources/views/app/_layouts/app.blade.php
@include('app._layouts.header')
@include('app._layouts.navbar')
@include('app._layouts.content')
@include('app._layouts.footer')

resources/views/app/_layouts/content.blade.php
<!-- Content Wrapper -->
<div class="container">
    <!-- Element yang akan dijadikan content -->
    @yield('content')
</div>

resources/views/app/_layouts/footer.blade.php
    <footer class="text-center p-1 bg-primary text-white fixed-bottom">
        <sup>©</sup>{{ now()->format('Y') }} Copyright : 
        <a class="text-white" href="https://hermawansafrin.com" target="_blank">
            Hermawan Safrin (KPB)
        </a>
    </footer>

    </body>
</html>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

@stack('footer_scripts')

resources/views/app/_layouts/header.blade.php
<!doctype html>
<html lang="id">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Latihan App</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        @stack('header_scripts')
    </head>
    <body>

resources/views/app/_layouts/navbar.blade.php
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand navbar-white" href="{{ route('index') }}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-white" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link {{ request()->routeIs('siswa.index') ? 'active' : '' }}" aria-current="page" href="{{ route('siswa.index') }}">Data Siswa</a>
            </div>
        </div>
    </div>
</nav>

resources/views/app/index.blade.php
<!-- Penanda template yang digunakan adalah dari app.blade.php -->
@extends('app._layouts.app')

@section('content')

<div class="card m-4">
    <div class="card-header bg-primary text-white">
        Komunitas Programmer Buton
    </div>
    <div class="card-body">
        <h5 class="card-title">Welcome !</h5>
        <p class="card-text">Ini adalah aplikasi pencatatan data siswa sederhana.</p>
        <a href="{{ route('siswa.index') }}" class="btn btn-primary btn-sm">
            Mulai <span class="fa fa-arrow-right"></span>
        </a>
    </div>
</div>

@endsection

resources/views/app/siswa/create.blade.php
<!-- Penanda template yang digunakan adalah dari app.blade.php -->
@extends('app._layouts.app')

@section('content')

<div class="card m-4">
    <div class="card-header bg-primary text-white">
        Tambah Data Siswa
    </div>
    <div class="card-body">

        @if($errors->any())

            <div class="alert alert-danger d-flex align-items-center" role="alert" style="max-height: 30px;">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div>
                    Terdapat Kendala Dalam Memasukkan Data Anda
                </div>
            </div>
        @endif

        <form action="{{ route('siswa.store') }}" method="POST" enctype="multipart/form-data">
            {{-- Kebutuhan keamanan, pengiriman token --}}
            @csrf

            {{-- Untuk Form Pengisian Nama Lengkap --}}
            <div class="mb-3">
                <label for="nama" class="form-label">
                    Nama Lengkap<span class="text-danger">*</span>
                </label>
                <input type="text" name="nama" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" 
                    id="nama" placeholder="Nama Lengkap.."
                    value="{{ old('name') }}" required
                    >
                @error('nama')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            {{-- Untuk Form Pengisian Nomor Induk --}}
            <div class="mb-3">
                <label for="nomor_induk" class="form-label">
                    Nomor Induk<span class="text-danger">*</span>
                </label>
                <input type="text" name="nomor_induk" class="form-control {{ $errors->has('nomor_induk') ? 'is-invalid' : '' }}" 
                    id="nomor_induk" placeholder="Nomor Induk.."
                    value="{{ old('nomor_induk') }}" required
                    >
                @error('nomor_induk')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            {{-- Untuk Form Pengisian Program Studi --}}
            <div class="mb-3">
                <label for="prodi_id" class="form-label">
                    Program Studi<span class="text-danger">*</span>
                </label>
                <select class="form-select {{ $errors->has('prodi_id') ? 'is-invalid' : '' }}" id="prodi_id" name="prodi_id" required>
                    <option value="">-- Pilih Program Studi --</option>
                    @foreach($prodis as $prodi)
                        <option value="{{ $prodi['id'] }}" {{ $prodi['id'] == old('prodi_id') ? 'selected' : '' }}>
                            {{ $prodi['nama'] }}
                        </option>
                    @endforeach
                </select>
                @error('prodi_id')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            <div class="mb-3">
                <label for="image" class="form-label">
                    Image<span class="text-danger">*</span>
                </label>
                <input class="form-control form-control-sm {{ $errors->has('is-invalid') ? 'is-invalid' : '' }}" 
                    id="image" type="file" required name="image"
                    accept="image/png, image/jpeg, image/jpg">
                @error('image')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            <button type="submit" class="btn btn-sm btn-primary">
                <i class="fa fa-save"></i> Simpan
            </button>

            {{-- Untuk Pengisian Gambar --}}
        </form>
    </div>
</div>

@endsection

resources/views/app/siswa/edit.blade.php
<!-- Penanda template yang digunakan adalah dari app.blade.php -->
@extends('app._layouts.app')

@section('content')

<div class="card m-4">
    <div class="card-header bg-primary text-white">
        Edit Data Siswa
    </div>
    <div class="card-body">

        @if($errors->any())
            <div class="alert alert-danger d-flex align-items-center" role="alert" style="max-height: 30px;">
                <svg class="bi flex-shrink-0 me-2" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                <div>
                    Terdapat Kendala Dalam Memasukkan Data Anda
                </div>
            </div>
        @endif

        <form action="{{ route('siswa.update', ['id' => $data['id']]) }}" method="POST" enctype="multipart/form-data">
            {{-- Kebutuhan keamanan, pengiriman token --}}
            @csrf
            @method('PUT')

            {{-- Untuk Form Pengisian Nama Lengkap --}}
            <div class="mb-3">
                <label for="nama" class="form-label">
                    Nama Lengkap<span class="text-danger">*</span>
                </label>
                <input type="text" name="nama" class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" 
                    id="nama" placeholder="Nama Lengkap.."
                    value="{{ $data['nama'] }}" required
                    >
                @error('nama')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            {{-- Untuk Form Pengisian Nomor Induk --}}
            <div class="mb-3">
                <label for="nomor_induk" class="form-label">
                    Nomor Induk<span class="text-danger">*</span>
                </label>
                <input type="text" name="nomor_induk" class="form-control {{ $errors->has('nomor_induk') ? 'is-invalid' : '' }}" 
                    id="nomor_induk" placeholder="Nomor Induk.."
                    value="{{ $data['nomor_induk'] }}" required
                    >
                @error('nomor_induk')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            {{-- Untuk Form Pengisian Program Studi --}}
            <div class="mb-3">
                <label for="prodi_id" class="form-label">
                    Program Studi<span class="text-danger">*</span>
                </label>
                <select class="form-select {{ $errors->has('prodi_id') ? 'is-invalid' : '' }}" id="prodi_id" name="prodi_id" required>
                    <option value="">-- Pilih Program Studi --</option>
                    @foreach($prodis as $prodi)
                        <option value="{{ $prodi['id'] }}" {{ $prodi['id'] == $data['prodi_id'] ? 'selected' : '' }}>
                            {{ $prodi['nama'] }}
                        </option>
                    @endforeach
                </select>
                @error('prodi_id')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            <div class="mb-3">
                <label for="image" class="form-label">
                    Image
                </label>
                <br/>
                <img src={{ asset('storage/images/'.$data['image']) }} class="img img-responsive" style="max-height: 40px;" />
                <br/>
                <span style="font-size:10px;">(Silahkan upload gambar baru jika ingin mengganti gambar terkini)</span>
                <input class="mt-2 form-control form-control-sm {{ $errors->has('is-invalid') ? 'is-invalid' : '' }}" 
                    id="image" type="file" name="image"
                    accept="image/png, image/jpeg, image/jpg">
                @error('image')
                    <span class="text-danger mt-1" style="font-size: 12px;">
                        {{ $message }}
                    </span>
                @enderror
            </div>

            <button type="submit" class="btn btn-sm btn-primary">
                <i class="fa fa-save"></i> Simpan
            </button>

            {{-- Untuk Pengisian Gambar --}}
        </form>
    </div>
</div>

@endsection

resources/views/app/siswa/index.blade.php
<!-- Penanda template yang digunakan adalah dari app.blade.php -->
@extends('app._layouts.app')

@section('content')

<div class="card m-4">
    <div class="card-header bg-primary text-white">
        Data Siswa
    </div>
    <div class="card-body">

        <a class="btn btn-sm btn-primary" href="{{ route('siswa.create') }}">
            <i class="fa fa-plus"></i> Tambah Data
        </a>

        @if(session('status'))
            <p class="text-success">
                {{ session('status') }}
            </p>
        @endif

        <table class="table table-hover table-responsive table-bordered mt-2">
            <thead>
                <tr>
                    <th class="text-center">#</th>
                    <th class="text-center">Nama Lengkap</th>
                    <th class="text-center">Nomor Induk</th>
                    <th class="text-center">Program Studi</th>
                    <th class="text-center">Foto</th>
                    <th class="text-center">Aksi</th>
                </tr>
            </thead>
            <tbody>
                {{-- Mencatatkan seluruh data siswa yang didapatkan --}}
                @forelse($datas as $data)
                    <tr>
                        <td class="text-center">{{ $loop->iteration }}</td>
                        <td class="text-center">{{ $data['nama'] }}</td>
                        <td class="text-center">{{ $data['nomor_induk'] }}</td>
                        <td class="text-center">{{ $data['prodi']['nama'] ?? '-' }}</td>
                        <td class="text-center">
                            <img class="img img-responsive" style="max-height:60px;" src="{{ asset('storage/images/'.$data['image']) }}">
                        </td>
                        <td class="text-center">
                            {{-- Button Edit --}}
                            <div>
                                <a class="btn btn-sm btn-warning m-1" href="{{ route('siswa.edit', ['id' => $data['id']]) }}">
                                    <i class="fa fa-pencil"></i> Edit
                                </a>
                            </div>

                            {{-- Button Delete --}}
                            <div>
                                <form method="POST" onsubmit="if(!confirm('Apakah anda yakin menghapus data ini ?')){return false;}" 
                                        action="{{ route('siswa.destroy', $data['id']) }}"
                                    >
                                    @csrf
                                    @method('DELETE')

                                    <button class="btn btn-sm btn-danger m-1" type="submit">
                                        <i class="fa fa-trash"></i> Hapus
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                {{-- Skenario jika kosong --}}
                @empty
                    <tr>
                        <td colspan="6" class="text-center">Data Kosong</td>
                    </tr>
                @endforelse
            </tbody>
        </table>
    </div>
</div>

@endsection